{% set name = "pinotdb" %}
{% set version = "0.4.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pinotdb-{{ version }}.tar.gz
  sha256: 700f43723e6e1038ef04881d62e86d17517556f512c14ebfb179d2832b2c1697

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    # missing from upstreams setup.py but test import fails without it
    - httpx
    - requests
    - six

test:
  imports:
    - pinotdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-pinot-dbapi/pinot-dbapi
  summary: Python DB-API and SQLAlchemy dialect for Pinot.
  license: MIT
  license_file: LICENSE
  doc_url: http://kylin.apache.org/docs/
  dev_url: https://github.com/python-pinot-dbapi/pinot-dbapi

extra:
  recipe-maintainers:
    - xylar
